
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Tue Nov 30 15:45:33 MST 2021
//----------------------------------------------------

package intface;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int Op_relacional = 11;
  public static final int Recorrido = 24;
  public static final int Llave_c = 18;
  public static final int Op_booleano = 14;
  public static final int Llave_a = 17;
  public static final int Detener = 30;
  public static final int T_dato = 2;
  public static final int Op_asignacion = 12;
  public static final int Espera = 38;
  public static final int Clase = 19;
  public static final int Func = 25;
  public static final int Start = 28;
  public static final int Notificar = 39;
  public static final int RotarR = 32;
  public static final int RotarL = 33;
  public static final int Retroceder = 31;
  public static final int Punto = 20;
  public static final int Cadena = 3;
  public static final int Parentesis_c = 16;
  public static final int Parentesis_a = 15;
  public static final int TextoSC = 36;
  public static final int EOF = 0;
  public static final int P_coma = 21;
  public static final int TextoSA = 35;
  public static final int error = 1;
  public static final int Encender = 26;
  public static final int Texto = 34;
  public static final int Caso = 6;
  public static final int Sensor = 37;
  public static final int ERROR = 40;
  public static final int Op_logico = 10;
  public static final int Avanzar = 29;
  public static final int Si_No = 5;
  public static final int Identificador = 22;
  public static final int Si = 4;
  public static final int Mientras = 7;
  public static final int Ciclo = 8;
  public static final int Op_incremento = 13;
  public static final int Apagar = 27;
  public static final int Numero = 23;
  public static final int Igual = 9;
}

